import React from 'react'

const Privacy = () => {
  return (
    <div className='p-20 text-white'>
        <div className='text-3xl font-semibold'>Privacy Policy</div>
        <div className='text-lg text-gray-200 mt-10'>Last updated: June 18, 2024 <br></br>
This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your 
information when You use the Service and tells You about Your privacy rights and how the law protects You.
We use Your Personal data to provide and improve the Service. By using the Service, You agree to the 
collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created 
with the help of the Privacy Policy Generator.</div>

<div className='text-3xl font-semibold mt-10'>Interpretation and Definitions</div>

<div className='text-2xl font-semibold mt-10'>Interpretation</div>

<div className='text-lg text-gray-200 mt-10'>The words of which the initial letter is capitalized have meanings defined under the following conditions. 
The following definitions shall have the same meaning regardless of whether they appear in singular or 
in plural.</div>

<div className='text-2xl font-semibold mt-10'>Definitions</div>

<div className='text-lg text-gray-200 mt-10'>For the purposes of this Privacy Policy:<br></br>
Account means a unique account created for You to access our Service or parts of our Service.<br></br>
Affiliate means an entity that controls, is controlled by or is under common control with a party, where 
&quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote 
      for election of directors or other managing authority.<br></br>
Application refers to Erebrus, the software program provided by the Company.<br></br>
Company (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to Erebrus.<br></br>
Country refers to: Delhi, India<br></br>
Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.<br></br>
Personal Data is any information that relates to an identified or identifiable individual.<br></br>
Service refers to the Application.<br></br>
Service Provider means any natural or legal person who processes the data on behalf of the Company.
      It refers to third-party companies or individuals employed by the Company to facilitate the Service, to 
      provide the Service on behalf of the Company, to perform services related to the Service or to assist the 
      Company in analyzing how the Service is used.<br></br>
Usage Data refers to data collected automatically, either generated by the use of the Service or from the 
     Service infrastructure itself (for example, the duration of a page visit).<br></br>
You means the individual accessing or using the Service, or the company, or other legal entity on behalf 
      of which such individual is accessing or using the Service, as applicable.</div>
    </div>
  )
}

export default Privacy